/*
 * This file is generated by jOOQ.
 */
package ru.psu.taskforjob.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.psu.taskforjob.jooq.tables.Employee;
import ru.psu.taskforjob.jooq.tables.Organization;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EMPLOYEE_PKEY = Indexes0.EMPLOYEE_PKEY;
    public static final Index ORGANIZATION_PKEY = Indexes0.ORGANIZATION_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EMPLOYEE_PKEY = Internal.createIndex("Employee_pkey", Employee.EMPLOYEE, new OrderField[] { Employee.EMPLOYEE.ID }, true);
        public static Index ORGANIZATION_PKEY = Internal.createIndex("Organization_pkey", Organization.ORGANIZATION, new OrderField[] { Organization.ORGANIZATION.ID }, true);
    }
}
