/*
 * This file is generated by jOOQ.
 */
package ru.psu.taskforjob.jooq.tables.records;


import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.psu.taskforjob.jooq.tables.Organization;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationRecord extends UpdatableRecordImpl<OrganizationRecord> implements Record3<UUID, String, UUID> {

    private static final long serialVersionUID = 1850228742;

    /**
     * Setter for <code>public.Organization.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Organization.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.Organization.OrgName</code>.
     */
    public void setOrgname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Organization.OrgName</code>.
     */
    public String getOrgname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.Organization.idHeadOrg</code>.
     */
    public void setIdheadorg(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Organization.idHeadOrg</code>.
     */
    public UUID getIdheadorg() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Organization.ORGANIZATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Organization.ORGANIZATION.ORGNAME;
    }

    @Override
    public Field<UUID> field3() {
        return Organization.ORGANIZATION.IDHEADORG;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getOrgname();
    }

    @Override
    public UUID component3() {
        return getIdheadorg();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getOrgname();
    }

    @Override
    public UUID value3() {
        return getIdheadorg();
    }

    @Override
    public OrganizationRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public OrganizationRecord value2(String value) {
        setOrgname(value);
        return this;
    }

    @Override
    public OrganizationRecord value3(UUID value) {
        setIdheadorg(value);
        return this;
    }

    @Override
    public OrganizationRecord values(UUID value1, String value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationRecord
     */
    public OrganizationRecord() {
        super(Organization.ORGANIZATION);
    }

    /**
     * Create a detached, initialised OrganizationRecord
     */
    public OrganizationRecord(UUID id, String orgname, UUID idheadorg) {
        super(Organization.ORGANIZATION);

        set(0, id);
        set(1, orgname);
        set(2, idheadorg);
    }
}
